### ISSUE TITLE
Better way to register tag prefixes

### ISSUE THREAD

**Issue by twsouthwick** [CoreWebForms/CoreWebForms#116]
# Background

Registering tag prefixes was something done in [`web.config`](https://learn.microsoft.com/dotnet/api/system.web.configuration.tagprefixinfo) in framework. This won't work going forward, so we need a way to communicate what namespaces a prefix refers to.

For context, this is what the registration looked like in `web.config`:

```xml
<system.web>  
  <pages>  
    <controls>  
      <!-- Searches all linked assemblies for the namespace -->  
      <add tagPrefix="MyTags1" namespace=" MyNameSpace "/>  
      <!-- Uses a specified assembly -->  
      <add tagPrefix="MyTags2" namespace="MyNameSpace"   
        assembly="MyAssembly"/>  
      <!-- Uses the specified source for the user control -->  
      <add tagprefix="MyTags3" tagname="MyCtrl" src="MyControl.ascx"/>  
    </controls>  
   </pages>  
</system.web>
```

## Design

The initial step is to allow prefixes to be registered by supplying a type from the namespace which will then be included in the compilation:

```cs
public static class WebFormsCompilerExtensions
{
    public static IWebFormsBuilder AddPrefix<T>(this IWebFormsBuilder builder, string prefix);
}

builder.Services.AddWebForms()
    .AddDynamicPages()
    .AddPrefix<ScriptManager>("asp") // For WebForms.Extensions
    .AddPrefix<ListView>("asp") // For WebForms.Extensions
    .AddPrefix<BundleReference>("webopt"); // For WebForms.Optimization
```

## Better Design

This does not work well for custom prefixes in the aspnet_compiler (static compilation). Therefore, we need a more data driven approach:

```cs
builder.Services.AddWebForms()
    .AddDynamicPages();
```

where `.AddDynamicPages()` will dynamically load from some source the types that are needed. This way, the dynamic pages can load them as well as the static compilation.

## Bonus

We could use the `Compiler.Generated` to add an interceptor that would override the call to `.AddDynamicPages()` so that it will not need reflection to load the types.

**Comment by twsouthwick** [comment]
I'm reopening this, because not all assemblies (especially third party) used these prefixes it seems so we should enable something to support those (looking at System.Web.Optimization.WebForms)

**Comment by twsouthwick** [comment]
Sometimes, something like this error appears as well:

```
System.Web.HttpParseException: Unknown server tag 'webopt:bundlereference'.
       ---> System.Web.HttpParseException: Unknown server tag 'webopt:bundlereference'.
       ---> System.Web.HttpException: Unknown server tag 'webopt:bundlereference'.
         at System.Web.UI.TemplateParser.ProcessError(String message)
         at System.Web.UI.TemplateParser.ProcessBeginTag(Match match, String inputText)
         at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding)
```

**Comment by birojnayak** [comment]
I just encountered another example like below... I would suggest to extend UseConfig to populate as tags and while loading assemblies add the control if namespace matches.

```
  <system.web>
    <siteMap>
      <providers>
        <add name="SamplesSiteMap" type="System.Web.XmlSiteMapProvider" siteMapFile="~/Samples.sitemap"/>
      </providers>
    </siteMap>
    <pages>
      <controls>
        <add namespace="InfoBlock" tagPrefix="samples"/>
      </controls>
    </pages>
    <trust level="Medium"/>
  </system.web>
```

**Comment by twsouthwick** [comment]
FYI I'm looking at this in the `feature/prefix-registrations` branch

It'll probably cause a reworking of the aspnet_compiler as well, but I think I have an idea of how to make it work.
