### ISSUE TITLE
porting wingtip toys complaining about FriendlyUrls at HostingEnvironmentStartupFilter

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#178]
Invoking PreApplicationStartMethodAttribute Microsoft.AspNet.FriendlyUrls.PreApplicationStartCode.Start in Microsoft.AspNet.FriendlyUrls, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
fail: Microsoft.Extensions.DependencyInjection.PreApplicationStartMethodExtensions.PreApplicationStartMethodStartupFilter[0]
      Failed to run PreApplicationStartMethodAttribute Microsoft.AspNet.FriendlyUrls.PreApplicationStartCode.Start in Microsoft.AspNet.FriendlyUrls, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.MissingMethodException: Method not found: 'Void System.Web.HttpApplication.RegisterModule(System.Type)'.
         at Microsoft.AspNet.FriendlyUrls.PreApplicationStartCode.Start()
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
         at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
         at Microsoft.Extensions.DependencyInjection.PreApplicationStartMethodExtensions.PreApplicationStartMethodStartupFilter.InvokeStartMethod(PreApplicationStartMethodAttribute startMethod)

**Comment by twsouthwick** [comment]
This is due to the pre application start failing if it fails to run and the friendly URLs are expecting to be able to register a module but the API doens't exist: HttpApplication.RegisterModule(System.Type)
