### ISSUE TITLE
Master.Page 

### ISSUE THREAD

**Issue by mason-chase** [CoreWebForms/CoreWebForms#259]
Hi

I'm trying to fix Master Page, there already an issue about the path using "\" instead of "/" that I have solved but 
now the Master Page is not properly loaded and is giving null error.

![image](https://github.com/CoreWebForms/CoreWebForms/assets/17309021/3da543ca-1d03-4ceb-a873-541bf9fea062)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SystemWebUISample.Pages.DynamicPage.OnInit(EventArgs arguments) in /UI/dynamic_page.aspx.cs:line 21
   at System.Web.UI.Control.InitRecursiveAsync(Control namingContainer, Page page) in D:\repos\core-web-forms\src\WebForms\UI\Control.cs:line 1883
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult() in D:\repos\core-web-forms\src\WebForms\Util\WithinCancellableCallbackTaskAwaitable.cs:line 48
   at System.Web.UI.Page.ProcessRequestMainAsync(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) in D:\repos\core-web-forms\src\WebForms\UI\Page.cs:line 5174
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult() in D:\repos\core-web-forms\src\WebForms\Util\WithinCancellableCallbackTaskAwaitable.cs:line 48
   at System.Web.UI.Page.ProcessRequestAsync(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) in D:\repos\core-web-forms\src\WebForms\UI\Page.cs:line 4947
   at System.Web.UI.Page.ProcessRequestAsync(HttpContext context) in D:\repos\core-web-forms\src\WebForms\UI\Page.cs:line 5875
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) in D:\repos\core-web-forms\src\WebForms\TaskAsyncHelper.cs:line 60
   at System.Web.UI.Page.AsyncPageEndProcessRequest(IAsyncResult result) in D:\repos\core-web-forms\src\WebForms\UI\Page.cs:line 5990
   at ASP.___UI_dynamic_page_aspx.EndProcessRequest(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.SystemWebAdapters.HttpHandlers.HandlerExtensions.RunHandlerAsync(IHttpHandler handler, HttpContext context) in D:\repos\core-web-forms\src\Handlers\HandlerExtensions.cs:line 19
   at System.Web.RequestEndExtensions.<>c.<<EnsureRequestEndThrows>b__0_0>d.MoveNext() in D:\repos\core-web-forms\src\Handlers\SystemWeb\RequestEndExtensions.cs:line 27
--- End of stack trace from previous location ---
   at System.Web.RequestEndExtensions.<>c.<<EnsureRequestEndThrows>b__0_0>d.MoveNext() in D:\repos\core-web-forms\src\Handlers\SystemWeb\RequestEndExtensions.cs:line 31
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.SystemWebAdapters.SessionLoadMiddleware.ManageStateAsync(HttpContext context, ISessionStateFeature feature)
   at Microsoft.AspNetCore.SystemWebAdapters.CurrentPrincipalMiddleware.SetUserAsync(HttpContext context)
   at Microsoft.AspNetCore.SystemWebAdapters.PreBufferRequestStreamMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by mason-chase** [comment]
I solved this problem by removing `AddCompiledPage` and adding `AddDynamicPage` at startup time, somehow they cannot be used together.
