### ISSUE TITLE
Page inheritance issue

### ISSUE THREAD

**Issue by mason-chase** [CoreWebForms/CoreWebForms#263]
Hi Everyone

Page with base type inheritance doesn't compile with main custom attributes
 
Imagine we create a class named BasePage which inherits from `System.Web.UI.Page` and has a public string property named `BasePageTitle`
 
Imagine we have a page named `page_with_base_type.aspx` which has a CodeBehind file named `page_with_base_type.aspx.cs`
 
The code behind file contains a class named `PageWithBaseType` which inherits from BasePage
 
Now when we try to set `BasePageTitle` property in `page_with_base_type.aspx` throws this exception:
 
```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.Web.HttpParseException: Error parsing attribute 'basepagetitle': Type 'System.Web.UI.Page' does not have a public property named 'basepagetitle'.
       ---> System.Web.HttpParseException: Error parsing attribute 'basepagetitle': Type 'System.Web.UI.Page' does not have a public property named 'basepagetitle'.
       ---> System.Web.HttpException: Error parsing attribute 'basepagetitle': Type 'System.Web.UI.Page' does not have a public property named 'basepagetitle'.
         at System.Web.UI.TemplateParser.ProcessError(String message) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 245
         at System.Web.UI.TemplateControlParser.ProcessUnknownMainDirectiveAttribute(String filter, String attribName, String value) in \source\repos\core-web-forms-private\src\WebForms\UI\TemplateControlParser.cs:line 270
         at System.Web.UI.PageParser.ProcessUnknownMainDirectiveAttribute(String filter, String attribName, String value) in \source\repos\core-web-forms-private\src\WebForms\UI\PageParser.cs:line 650   
         at System.Web.UI.TemplateParser.ProcessMainDirective(IDictionary mainDirective) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 2188
         at System.Web.UI.TemplateControlParser.ProcessMainDirective(IDictionary mainDirective) in \source\repos\core-web-forms-private\src\WebForms\UI\TemplateControlParser.cs:line 203
         at System.Web.UI.PageParser.ProcessMainDirective(IDictionary mainDirective) in \source\repos\core-web-forms-private\src\WebForms\UI\PageParser.cs:line 335
         at System.Web.UI.TemplateParser.ProcessDirective(String directiveName, IDictionary directive) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 2047        
         at System.Web.UI.BaseTemplateParser.ProcessDirective(String directiveName, IDictionary directive) in \source\repos\core-web-forms-private\src\WebForms\Compilation\BaseTemplateParser.cs:line 275 
         at System.Web.UI.TemplateControlParser.ProcessDirective(String directiveName, IDictionary directive) in \source\repos\core-web-forms-private\src\WebForms\UI\TemplateControlParser.cs:line 168    
         at System.Web.UI.PageParser.ProcessDirective(String directiveName, IDictionary directive) in \source\repos\core-web-forms-private\src\WebForms\UI\PageParser.cs:line 325
         at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 1140
         --- End of inner exception stack trace ---
         at System.Web.UI.TemplateParser.ProcessException(Exception ex) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 273
         at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 1144
         at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 940
         --- End of inner exception stack trace ---
         at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 991
         at System.Web.UI.TemplateParser.ParseReader(StreamReader reader, VirtualPath virtualPath) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 889
         at System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 868
         at System.Web.UI.TemplateParser.ParseFile(String physicalPath, String virtualPath) in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 829
         at System.Web.UI.TemplateParser.ParseInternal() in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 814
         at System.Web.UI.TemplateParser.Parse() in \source\repos\core-web-forms-private\src\WebForms\Compilation\TemplateParser.cs:line 792
         at System.Web.UI.DependencyParser.Parse() in \source\repos\core-web-forms-private\src\WebForms\Compilation\BatchParser.cs:line 113
         at WebForms.Compiler.Dynamic.SystemWebCompilation.GetParsersToCompile(IEnumerable`1 files, SystemWebCompilationUnit compilationUnit)+MoveNext() in \source\repos\core-web-forms-private\src\Compiler.Dynamic\SystemWebCompilation.cs:line 97
         at WebForms.Compiler.Dynamic.SystemWebCompilation.CompileAllPages(ICompilationStrategy strategy, CancellationToken token) in \source\repos\core-web-forms-private\src\Compiler.Dynamic\SystemWebCompilation.cs:line 56
         at WebForms.Compiler.Dynamic.SystemWebCompilation.WebForms.Compiler.Dynamic.IWebFormsCompiler.CompilePages(ICompilationStrategy outputProvider, CancellationToken token) in \source\repos\core-web-forms-private\src\Compiler.Dynamic\SystemWebCompilation.cs:line 269
         at WebForms.Compiler.Dynamic.DynamicSystemWebCompilation.CompilePages(CancellationToken token) in \source\repos\core-web-forms-private\src\Compiler.Dynamic\DynamicSystemWebCompilation.cs:line 76
         at WebForms.Compiler.Dynamic.WebFormsCompilationService.ProcessChanges(CancellationToken token) in \source\repos\core-web-forms-private\src\Compiler.Dynamic\WebFormsCompilationService.cs:line 61
         at WebForms.Compiler.Dynamic.WebFormsCompilationService.ExecuteAsync(CancellationToken stoppingToken) in \source\repos\core-web-forms-private\src\Compiler.Dynamic\WebFormsCompilationService.cs:line 46
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```
 
I think it should detect BasePage as type but it is currently detecting System.Web.UI.Page as type.

**Comment by twsouthwick** [comment]
I believe the underlying issue is that if the base type is not already compiled, it is not available to set any properties on. I'm adding a test in #317, but it is currently disabled.
