### ISSUE TITLE
Pages/Controls with custom base classes "fail" to compile

### ISSUE THREAD

**Issue by AvremelM** [CoreWebForms/CoreWebForms#382]
Any Page, UserControl, or MasterPage that inherits from a custom base class (in the main assembly) that extends `Page`, `UserControl` or `MasterPage` doesn't compile correctly.

More precisely, it actually compiles (apparently correctly) to a dll, but the code that tries to load the `Type` from the dll fails to load the dll's references to the main assembly.

To reproduce (in `WebFormsSample.Static` project): 

* Add `public class MasterBase : System.Web.UI.MasterPage { }` to `Helpers.cs` (or a new file)
* Modify `Site.Master.cs` to inherit from `MasterBase`.
* Build `WebFormsSample.Static` project
* Error
<details><summary>End of build log</summary>
<p>

```
...
...
info: WebForms.Compiler.Dynamic.PageAssemblyLoadContext[0] Created assembly for WebForms:/Site.Master:1
fail: WebForms.Compiler.Dynamic.SystemWebCompilation[0] Failed to compile /Site.Master System.InvalidOperationException: No type found    at WebForms.Compiler.Dynamic.SystemWebCompilation.CreateCompiledPage(SystemWebCompilationUnit cu, Compilation compilation, VirtualPath virtualPath, String typeName, IEnumerable`1 embedded, IEnumerable`1 assemblies, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 231    at WebForms.Compiler.Dynamic.SystemWebCompilation.InternalCompilePage(SystemWebCompilationUnit compiledPages, DependencyParser parser, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 153
crit: WebForms.Compiler.StaticCompilationService[0] Exception while compiling occurred System.InvalidOperationException: No type found    at WebForms.Compiler.Dynamic.SystemWebCompilation.CreateCompiledPage(SystemWebCompilationUnit cu, Compilation compilation, VirtualPath virtualPath, String typeName, IEnumerable`1 embedded, IEnumerable`1 assemblies, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 231    at WebForms.Compiler.Dynamic.SystemWebCompilation.InternalCompilePage(SystemWebCompilationUnit compiledPages, DependencyParser parser, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 153    at WebForms.Compiler.Dynamic.SystemWebCompilation.CompileAllPages(ICompilationStrategy strategy, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 58    at WebForms.Compiler.Dynamic.SystemWebCompilation.WebForms.Compiler.Dynamic.IWebFormsCompiler.CompilePages(ICompilationStrategy outputProvider, CancellationToken token) in ~\CoreWebForms\src\Compiler.Dynamic\SystemWebCompilation.cs:line 269    at WebForms.Compiler.StaticCompilationService.ExecuteAsync(CancellationToken stoppingToken) in ~\CoreWebForms\tools\aspnet_compiler\StaticCompilationService.cs:line 41
info: WebForms.Compiler.Dynamic.PageAssemblyLoadContext[0] Unloading assembly load context for WebForms:/loadusercontrol.aspx:1
info: WebForms.Compiler.Dynamic.PageAssemblyLoadContext[0] Unloading assembly load context for WebForms:/InsideTestUserControl.ascx:1
info: WebForms.Compiler.Dynamic.PageAssemblyLoadContext[0] Unloading assembly load context for WebForms:/TestUserControl.ascx:1
info: WebForms.Compiler.Dynamic.PageAssemblyLoadContext[0] Unloading assembly load context for WebForms:/Site.Master:1
15>WebForms.Compiler.Static.targets(100,5): Error  : There was an error compiling WebForms assets.
``` 

</p>
</details>

**Comment by AvremelM** [comment]
Possibly related to #263?
